### PR TITLE
Change UpdateNotifier virion author to ifera-mc

### PR DESCRIPTION
**Pull request by AIPTU**

### CODE REVIEW

**Comment by KygekDev** [comment]
We will merge this commit if Poggit can't find the UpdateNotifier virion when we make a commit on this virion repository.

**Comment by AIPTU** [comment]
https://poggit.pmmp.io/ci/Ifera/ScoreHud/~/dev:69
Then they changes to
https://github.com/Ifera/ScoreHud/commit/ba941004aef8fd567d425b96db9d803c77e09f17

**Comment by KygekDev** [comment]
> https://poggit.pmmp.io/ci/Ifera/ScoreHud/~/dev:69
> Then they changes to
> [Ifera/ScoreHud@ba94100](https://github.com/Ifera/ScoreHud/commit/ba941004aef8fd567d425b96db9d803c77e09f17)

Okay, thanks for your reply. We will merge this pull request _now_.

**Comment by KygekDev** [comment]
Thanks for your contribution!

**Pull request merged**
